### ISSUE TITLE
Timing Out

### ISSUE THREAD

**Issue by mikeyaworski** [nwoodthorpe/GRTUnofficialLiveAPI#1]
I'm writing an AWS Lambda Function (developing an Alexa Skill) that uses this API, but midway through developing, the API request just started timing out after 3 seconds.

I tested on a different environment with a different IP address (not on AWS), and it doesn't time out. I recall you stating that you blacklist IPs that are abusing the service. Does this fall under that category? Should it?

Edit: It now lets me make requests again. But before you close this issue (because this may happen again), maybe have a look into whether or not this was a blacklisting issue.

**Comment by nwoodthorpe** [comment]
I've checked the blacklist, it shouldn't be causing you any issues. May have been a server blip, I'll look into it!
